import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import dynamic from "next/dynamic";
import { useEffect, useState } from "react";

const LazyButton = dynamic(
  () =>
    import("remote/Button").catch(() => ({
      default: () => <p>Failed to load</p>,
    })),
  {
    ssr: false,
    loading: () => <p>Loading...</p>,
  }
);

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [message, setMessage] = useState("");

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await fetch("http://localhost:3001/api/hello");
        if (!response.ok) {
          throw new Error("Network response was not ok");
        }
        const data = await response.json();
        console.log(data);
        setMessage(data.message);
      } catch (error) {
        console.error("Error fetching data:", error);
      }
    };

    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>Home App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Home app</h1>
        <p>Message from remote: {message}</p>

        <LazyButton />
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  return {
    props: {},
  };
};
